name: frontend
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.3
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.6
  url_launcher: ^6.2.2
  mask_text_input_formatter: ^2.7.0
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2
  flutter_easyloading: ^3.0.5
  dio: ^5.7.0
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  package_info_plus: ^6.0.0
  device_info_plus: ^9.1.1
  intl: ^0.19.0
  pdf: ^3.10.7
  cached_network_image: ^3.3.1
  table_calendar: ^3.1.2
  local_auth: ^2.2.0
  local_auth_darwin: ^1.3.1
  local_auth_android: ^1.0.39
  syncfusion_flutter_pdfviewer: 24.2.8
  pin_code_fields: ^8.0.1
  syncfusion_flutter_core: ^24.1.47
  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.15
  overlay_support: ^2.1.0
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^17.0.0
  dropdown_search: ^5.0.6
  flutter_native_splash: ^2.3.9
  mobile_scanner: ^5.1.1
  qr_scanner_overlay: ^0.0.2
  searchfield: ^1.1.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/